
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: postgres
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: icertus_development

test:
  <<: *default
  database: icertus_test

production:
  <<: *default
  database: icertus_production
  username: icertus
  password: <%= ENV["ICERTUS_DATABASE_PASSWORD"] %>
